### ISSUE TITLE
B85 ou H81?

### ISSUE THREAD

**Issue by luizsnike** [luchina-gabriel/EFI-X99-HUANANZHI-8M-F-B85-INTEL-XEON-V3-RX-580-8GB#2]
No nome fala B85, mas na descrição fala H81, qual o chip correto dessa EFI?

Tentei na minha MR9A Pro Max V2 e nao subiu certo, ela tem B85.

**Comment by luchina-gabriel** [comment]
Estas placa precisa criar EFI nova, tem vídeo para membros ensinando, este aqui: 

Do ZERO ao Hackintosh com macOS Ventura - Criando EFI Opencore para X99 [Huananzhi QD4]
https://youtu.be/2zJt0Xa17iM

Apesar de ser a Huananzhi, ensino a criar os patches e tudo mais. Vale para qualquer x99.
